### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by danielSanchezQ** [danielSanchezQ/warp-reverse-proxy#8]
It is published the first version of the library in crates.io, it still can be improved and I will be working on the next features/fixes:

- [ ] Add better documentation
- [ ] Add usage examples
- [ ] Improve testing for corner cases
- [ ] Add usage examples
- [ ] Try to catch the client IP address and attach it to the `X-Forwarded-For` header
- [ ] Leverage errors (bubble up errors instead of current unwrappings)

**Comment by danielSanchezQ** [comment]
Added better docs in #12

**Comment by rahulmr** [comment]
Please do add some complete and working examples. Also, examples where we can proxy to outside servers
